### ISSUE TITLE
N23: rename all version numbers to 23

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#89]

**Comment by UriHerrera** [comment]
I've updated the version numbers; only the wallpaper says 22, but I don't have the source of the image to edit it.

I built an ISO with these changes on the 23rd of September.

https://pub.netrunner.com/.testing/netrunner-next-amd64_2022.09.23-09.42.iso

__I installed neofetch because it displays the information from `/etc/os-release`__

----

## Screenshots

![VirtualBox_Netrunner_03_10_2022_21_28_24](https://user-images.githubusercontent.com/3053525/193722083-842839f7-2305-486a-8606-31e188ac8bbc.png)
![VirtualBox_Netrunner_03_10_2022_21_30_35](https://user-images.githubusercontent.com/3053525/193722084-9cc683e5-dc47-4a1a-a570-6cf09f78f325.png)
![VirtualBox_Netrunner_03_10_2022_21_30_42](https://user-images.githubusercontent.com/3053525/193722085-58162ce4-3a9d-4e8e-8be9-a0af5fd87e26.png)
![VirtualBox_Netrunner_03_10_2022_21_30_48](https://user-images.githubusercontent.com/3053525/193722087-13730c40-8e52-40a0-9f1b-77cde9dca45d.png)
![VirtualBox_Netrunner_03_10_2022_21_31_12](https://user-images.githubusercontent.com/3053525/193722091-dbedbf9b-5a75-4115-9d37-7159a666d693.png)

**Comment by star-buck** [comment]
awesome will see to update wallpaper final
